### ISSUE TITLE
Ability to ignore disable entities

### ISSUE THREAD

**Issue by chrisdrackett** [Digital-Alchemy-TS/type-writer#23]
I have a lot of entities, but a majority of them are disabled in HASS. Right now it seems all these are being pulled into the types leading to a large file. I'd love to give typescript a break and reduce the load, so it would be great if there was an option to just not import anything disabled.

**Comment by zoe-codez** [comment]
Should be a simple filtering operation. I'll pick it up next time I make changes to the code. In case someone wants to take it on sooner, happy to accept a PR that implements it with a config gate

**Comment by zoe-codez** [comment]
Disabled a few entities & cannot find in output anymore. Seems done!
