### ISSUE TITLE
Missing comma in generated source file

### ISSUE THREAD

**Issue by solidsystem** [Digital-Alchemy-TS/type-writer#34]
## 🐜 Bug description

With version 24.8.2 it seems the generated code does not compile.

It looks like there is some commas missing at this location in version 24.8.2:

https://github.com/Digital-Alchemy-TS/type-writer/pull/32/files#diff-e717819cc15a73680d789cc92985aa4f6513662d71134926caafb76e7bbdd12aR58

Previous values had comma at the end:
```
`   ActionableNotification,`,
`  AndroidActionableNotification,`,
`  AppleActionableNotification,`,
```
New ones don't:
```
        `  AndroidNotificationData`,
        `  AppleNotificationData`,
        `  NotificationData`,
```

**Comment by zoe-codez** [comment]
Big derp, sorry about that. `24.9.1` resolves this

**Comment by solidsystem** [comment]
Thanks for fixing!
